---
extends: default

ignore:
  - pkg/generators/templates

rules:
  # YAML that will be inlined within runtime-init must not have document separators.
  document-start: disable

  line-length:
    max: 120
    level: warning
